#! /bin/sh


sxhkd &
compton --config ~/.config/compton.conf -b &
feh --bg-scale ~/.config/wallpaper/fireforce.png &
fcitx -dr &
# light-locker &
$HOME/.config/polybar/launch.sh
wmname LG3D

killall telegram; telegram &
/home/vbalien/SVP\ 4/SVPManager &
transgui &
nm-applet &

# TrackPoint Speed
# xinput --set-prop "10" "libinput Accel Speed" -0.4
# xinput --set-prop "9" "libinput Accel Speed" -0.8

# Default Cursor
xsetroot -cursor_name left_ptr


bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         5
bspc config window_gap           10
bspc config top_padding          25

bspc config normal_border_color "#cccccc"
bspc config focused_border_color "#dd5555"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a '*:zathura' state=tiled
