#! /bin/sh

# Runs a program unless that program is already running
function conditional_run {
  local program_name=$1

  ps_result=$(ps aux \
      | grep "${program_name}" \
      | grep -v "grep" \
      | wc -l
      )
  if [ $ps_result -eq 0 ]; then
      echo "Running $program_name"
      `$program_name` &
  else
      echo "$program_name already running"
  fi
}


compton --config ~/.config/compton.conf -b &
feh --bg-scale ~/.config/wallpaper/fireforce.png &
fcitx -dr &
# light-locker &
$HOME/.config/polybar/launch.sh
wmname LG3D

killall xss-lock; xss-lock -- i3lock-fancy -n &

conditional_run SVPManager
conditional_run transgui
conditional_run nm-applet
conditional_run blueman-applet
conditional_run telegram
conditional_run sxhkd

# Elan input setting
xinput set-prop 'Elan Touchpad' 319 1 # tap to click

# Default Cursor
xsetroot -cursor_name left_ptr



bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8 9
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9

bspc config border_width         5
bspc config window_gap           10
bspc config top_padding          25

bspc config normal_border_color "#cccccc"
bspc config focused_border_color "#dd5555"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc rule -a '*:zathura' state=tiled
